server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
- job_name: docker
  pipeline_stages:
    - json:
        expressions:
          output: log
          stream: stream
          timestamp: time
          name: attrs.name
          id: attrs.tag
    - labels:
        stream: stream
        name: name
        id: id
    - output:
        source: output
  static_configs:
  - targets:
      - localhost
    labels:
      job: dockerlogs
      __path__: /dockerlogs/*/*log